# Generated by Django 3.2.9 on 2021-12-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronedata',
            name='drone_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.dronetype'),
        ),
        migrations.AddField(
            model_name='dronedata',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.pilotdata'),
        ),
    ]
