# Generated by Django 3.2.9 on 2021-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211214_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='dronedata',
            name='reg_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='endurance_min',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='model_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='sl_no',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='type',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pilotdata',
            name='country',
            field=models.CharField(default='India', max_length=25),
        ),
    ]
