# Generated by Django 3.2.9 on 2021-12-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211215_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dronedata',
            old_name='total_flight_time',
            new_name='total_flight_time_min',
        ),
    ]
