# Generated by Django 3.2.9 on 2021-12-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_total_flight_time_dronedata_total_flight_time_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronetype',
            name='model_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
