# Generated by Django 3.2.9 on 2021-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dronetype_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotdata',
            name='address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pilotdata',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pilotdata',
            name='phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pilotdata',
            name='skill',
            field=models.IntegerField(default=0),
        ),
    ]
